import { Product } from "./types/product";

const goods: Product[] = [
  {
    id: "1",
    img: "img/red1.jpg",
    name: "Halftone ida red with flowers",
    cost: 6,
    color: "red",
    origin: "Italy",
    year: 2018,
    type: ["children", "clothing", "decorative"],
    favorite: false,
    stockCount: 10,
  },
  {
    id: "2",
    img: "img/red2.jpg",
    name: "Bordeaux polyester",
    cost: 18,
    color: "red",
    origin: "Germany",
    year: 2019,
    type: ["curtain", "furniture"],
    favorite: false,
    stockCount: 10,
  },
  {
    id: "3",
    img: "img/red3.jpg",
    name: "Ida red with flowers",
    cost: 39,
    color: "red",
    origin: "China",
    year: 2020,
    type: ["curtain", "furniture", "decorative"],
    favorite: false,
    stockCount: 10,
  },
  {
    id: "4",
    img: "img/blue1.jpg",
    name: "Navy halftone with flowers",
    cost: 67,
    color: "blue",
    origin: "Italy",
    year: 2021,
    type: ["curtain", "furniture", "decorative"],
    favorite: false,
    stockCount: 10,
  },
  {
    id: "5",
    img: "img/blue2.jpg",
    name: "Blue polyester with applique",
    cost: 92,
    color: "blue",
    origin: "India",
    year: 2020,
    type: ["children", "clothing"],
    favorite: false,
    stockCount: 10,
  },
  {
    id: "6",
    img: "img/green1.jpg",
    name: "Green rudolfine",
    cost: 57,
    color: "green",
    origin: "Germany",
    year: 2018,
    type: ["clothing", "decorative"],
    favorite: false,
    stockCount: 10,
  },
  {
    id: "7",
    img: "img/green2.jpg",
    name: "Plain light green gloss satin",
    cost: 28,
    color: "green",
    origin: "Italy",
    year: 2019,
    type: ["decorative", "clothing", "furniture"],
    favorite: false,
    stockCount: 10,
  },
  {
    id: "8",
    img: "img/pink1.jpg",
    name: "Pink rudolfine",
    cost: 88,
    color: "pink",
    origin: "China",
    year: 2022,
    type: ["decorative", "clothing", "children"],
    favorite: false,
    stockCount: 10,
  },
  {
    id: "9",
    img: "img/yellow1.jpg",
    name: "Gelb canvas",
    cost: 71,
    color: "yellow",
    origin: "China",
    year: 2021,
    type: ["curtain", "clothing", "furniture"],
    favorite: false,
    stockCount: 10,
  },
  {
    id: "10",
    img: "img/yellow2.jpg",
    name: "Muslin double gauze",
    cost: 18,
    color: "yellow",
    type: ["clothing"],
    origin: "Germany",
    year: 2018,
    favorite: false,
    stockCount: 10,
  },
];

export default goods;
